# ---------------------------------------------------- #
# Note: this file originates in template-action-docker #
# ---------------------------------------------------- #

name: push

on:
  - push
  - workflow_dispatch

permissions: read-all

jobs:
  main:
    uses: ahmadnassri/actions/.github/workflows/push-action-docker.yml@master
    secrets:
      public-key: ${{ secrets.SSH_PUBLIC_KEY }}
      private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    with:
      sign-commits: true
    permissions:
      contents: write
      statuses: write
      packages: write
      pull-requests: write
